// src/components/admin/AdminSettings.js
// 2.7 + 3.2 — Three sections: Inventory, Global Pricing, Site Notice, Activity Log.

import React, { useState, useEffect, useRef, useMemo } from 'react';
import '../../styles/classes.css';
import { get, put, del } from 'aws-amplify/api';
import SecurityPinModal from './SecurityPinModal';
import { coursesInfo as hardcodedCourses, courseCanonicalItems } from '../../config/courseData';

async function apiFetch(path) {
  const op = get({ apiName: 'checkoutApi', path });
  const { body } = await op.response;
  return body.json();
}

async function apiPut(path, data) {
  const op = put({ apiName: 'checkoutApi', path, options: { body: data } });
  const { body } = await op.response;
  return body.json();
}

async function apiDelete(path, params) {
  const qs = new URLSearchParams(params).toString();
  const op = del({ apiName: 'checkoutApi', path: `${path}?${qs}` });
  const { body } = await op.response;
  return body.json();
}

// Fallback category for Modulos entries whose name wasn't generated by any
// CourseSettings record (e.g. because the schedule option doesn't match the
// time regex). Order matters: check "Maestrías" (hair, plural) before
// "Maestría" (makeup, singular) to avoid a prefix collision.
// Prefixes match the exact names stored by the customer checkout (DB_KEY_MAP in CourseDetails.js).
// "Maestrías" (plural) = hair; "Maestría" (singular) = makeup — order matters to avoid collision.
const ORPHAN_PREFIX_MAP = [
  { prefix: 'master waves intensivo',             category: 'hair'   },
  { prefix: 'master waves',                       category: 'hair'   },
  { prefix: 'peinados para eventos',              category: 'hair'   },
  { prefix: 'maestrías en novias y tendencias',   category: 'hair'   },
  { prefix: 'curso completo peinado',             category: 'hair'   },
  { prefix: 'pieles perfectas',                   category: 'makeup' },
  { prefix: 'maquillaje social',                  category: 'makeup' },
  { prefix: 'maestría en novias y tendencias',    category: 'makeup' },
  { prefix: 'curso completo maquillaje',          category: 'makeup' },
];

function resolveOrphanCategory(courseName) {
  const lower = courseName.toLowerCase();
  for (const { prefix, category } of ORPHAN_PREFIX_MAP) {
    if (lower.startsWith(prefix)) return category;
  }
  return null;
}

export default function AdminSettings() {
  const [seatList,       setSeatList]       = useState([]);  // raw Modulos rows: [{ moduleId, courseName, seats }]
  const [itemNameMap,    setItemNameMap]     = useState({});  // { itemName: { moduleId, seats } }
  const [courseSettings, setCourseSettings] = useState([]);  // all CourseSettings records
  const [settings,       setSettings]       = useState({});  // { settingKey: { ... } }
  const [loading,        setLoading]        = useState(true);
  const [error,          setError]          = useState(null);

  // Permanent DynamoDB IDs — must stay in sync with moduleIds in app.js.
  // Admin always writes to these IDs so checkout reads the same item.
  const PERMANENT_IDS = {
    'Master Waves 2PM a 4PM':                       '1Qk3ZTR8Mu9cvxdGGVYER',
    'Master Waves 6PM a 8PM':                       '2lAsVcE1N0gZl4Iiki3GP',
    'Master Waves Intensivo 1 Día 9AM a 4PM':       'intensivo-mw-1dia-9am4pm',
    'Peinados Para Eventos 2PM a 4PM':              '3ASSXgw602WiVe4HpldAP',
    'Peinados Para Eventos 6PM a 8PM':              '4rfA37M4cMXl6iO6bSwW4',
    'Maestrías en Novias y Tendencias 6PM a 8PM':   '6gh7uXaEGwKGk5Ut2xUOR',
    'Curso Completo Peinado 2PM a 4PM':             '7PgoPXqtemmdd1EpAhUMq',
    'Curso Completo Peinado 6PM a 8PM':             '8o9SHzxxK9yJVOVds7idf',
    'Pieles Perfectas 2PM a 4PM':                   '92D9cfiMeVtav2HYhUA9Z',
    'Pieles Perfectas 6PM a 8PM':                   '931hGzkK3hqpEvLB4C4iSm',
    'Maquillaje Social 2PM a 4PM':                  '93hiNbQKXTUAUAYdRFeeN3',
    'Maquillaje Social 6PM a 8PM':                  '94wZBdWsajdmn30YInrflP',
    'Maestría en Novias y Tendencias 6PM a 8PM':    '96xtPAxBtiDBNK01FJbwMl',
    'Curso Completo Maquillaje 2PM a 4PM':          '98aq0pkxn574RJGFiIB4CQ',
    'Curso Completo Maquillaje 6PM a 8PM':          '991XsOABf2lp5CdSMm21YR3',
  };

  // Stable IDs for new (not-yet-in-Modulos) course+schedule combos.
  // Uses permanent IDs for known courses; falls back to a random per-session
  // ID for any truly unknown entry so SeatRow state doesn't reset mid-session.
  const newIdCache = useRef({});
  function stableId(itemName) {
    if (PERMANENT_IDS[itemName]) return PERMANENT_IDS[itemName];
    if (!newIdCache.current[itemName]) {
      newIdCache.current[itemName] = `ns_${Math.random().toString(36).slice(2, 14)}`;
    }
    return newIdCache.current[itemName];
  }

  useEffect(() => {
    Promise.all([
      apiFetch('/admin/seats'),
      apiFetch('/admin/site-settings'),
      apiFetch('/admin/courses'),
    ])
      .then(([seatsData, settingsData, coursesData]) => {
        // Process Modulos rows
        const processed = [];
        const iMap = {};
        for (const item of seatsData) {
          for (const key of Object.keys(item)) {
            if (key === 'id') continue;
            const entry = { moduleId: item.id, courseName: key, seats: Number(item[key]) };
            processed.push(entry);
            if (key !== 'Kit de pieles perfectas') {
              iMap[key] = { moduleId: item.id, seats: Number(item[key]) };
            }
          }
        }
        processed.sort((a, b) => a.courseName.localeCompare(b.courseName));
        setSeatList(processed);
        setItemNameMap(iMap);
        setCourseSettings(coursesData || []);

        const map = {};
        for (const s of settingsData) map[s.settingKey] = s;
        setSettings(map);
      })
      .catch(() => setError('Error al cargar la configuración.'))
      .finally(() => setLoading(false));
  }, []);

  // Build the seat configuration grouped by category from CourseSettings.
  // Modulos data is used only as an overlay for existing seat counts.
  const seatConfig = useMemo(() => {
    const hair    = [];
    const makeup  = [];
    const other   = [];
    const usedItemNames = new Set();

    for (const course of courseSettings) {
      if (course.deleted) continue;
      if (!course.courseName) continue;
      const cat = course.category || hardcodedCourses[course.courseId]?.category;
      if (cat === 'online') continue;
      const schedOpts = course.scheduleOptions;
      if (!Array.isArray(schedOpts) || schedOpts.length === 0) continue;

      const bucket = cat === 'hair'   ? hair
                   : cat === 'makeup' ? makeup
                   : other;

      // Use canonical names (matching DB_KEY_MAP / backend moduleIds) for known
      // hardcoded courses. For admin-created courses without a canonical entry,
      // build the item name as "<courseName> <scheduleOption>" — same format
      // used by the customer checkout fallback in CourseDetails.js.
      const canonicalNames = courseCanonicalItems[course.courseId];
      const itemNames = canonicalNames
        || schedOpts.map(opt => `${course.courseName} ${opt}`);

      for (const itemName of itemNames) {
        usedItemNames.add(itemName);
        const existing = itemNameMap[itemName];
        // PERMANENT_IDS always wins — ensures admin writes to the same DynamoDB
        // item the checkout reads, even if a stale entry exists under a different ID.
        bucket.push({
          key:      itemName,
          label:    itemName,
          moduleId: PERMANENT_IDS[itemName] || existing?.moduleId || stableId(itemName),
          seats:    existing?.seats ?? 0,
          isNew:    !existing,
        });
      }
    }

    // Flat set of every canonical item name across all courses.
    // Any Modulos entry that matches a known course prefix but is NOT in this set
    // is a stale/retired item → treat as orphan (deletable), not as an active seat row.
    const allCanonicalNames = new Set(Object.values(courseCanonicalItems).flat());

    const orphaned = [];
    for (const s of seatList) {
      if (s.courseName === 'Kit de pieles perfectas') continue;
      if (usedItemNames.has(s.courseName)) continue;

      const entry = {
        key:        `${s.moduleId}-${s.courseName}`,
        label:      s.courseName,
        moduleId:   s.moduleId,
        courseName: s.courseName,
        seats:      s.seats,
        isNew:      false,
      };

      const prefixMatch = ORPHAN_PREFIX_MAP.find(
        ({ prefix }) => s.courseName.toLowerCase().startsWith(prefix)
      );

      // If this entry belongs to a known course but isn't in the canonical list,
      // it's a retired item — show it as deletable, not as an active seat row.
      if (prefixMatch && allCanonicalNames.has(s.courseName)) {
        if      (prefixMatch.category === 'hair')   hair.push(entry);
        else if (prefixMatch.category === 'makeup') makeup.push(entry);
        else                                        orphaned.push(entry);
      } else {
        orphaned.push(entry);
      }
    }

    return { hair, makeup, other, orphaned };
  }, [courseSettings, itemNameMap, seatList]); // eslint-disable-line react-hooks/exhaustive-deps

  if (loading) return <p style={{ color: '#aaa', fontFamily: FONT }}>Cargando configuración…</p>;
  if (error)   return <p style={{ color: '#c62828', fontFamily: FONT }}>{error}</p>;

  const kit = seatList.find(s => s.courseName === 'Kit de pieles perfectas');

  return (
    <div>
      <h1 className="admin-page-title">Configuración</h1>

      {/* ── Inventory: Kit ── */}
      <Section title="Inventario — Kit de Maquillaje">
        {kit
          ? <SeatRow label="Kit de pieles perfectas" moduleId={kit.moduleId} courseName={kit.courseName} initialSeats={kit.seats} />
          : <p style={emptyStyle}>Kit no encontrado en la base de datos.</p>
        }
      </Section>

      {/* ── Inventory: Hair courses ── */}
      <Section title="Lugares por Curso — Cabello (Hair)">
        {seatConfig.hair.length === 0
          ? <p style={emptyStyle}>No hay cursos de cabello con horarios configurados.</p>
          : seatConfig.hair.map(s => (
            <SeatRow
              key={s.key}
              label={s.label}
              moduleId={s.moduleId}
              courseName={s.label}
              initialSeats={s.seats}
              isNew={s.isNew}
            />
          ))
        }
      </Section>

      {/* ── Inventory: Makeup courses ── */}
      <Section title="Lugares por Curso — Maquillaje (Makeup)">
        {seatConfig.makeup.length === 0
          ? <p style={emptyStyle}>No hay cursos de maquillaje con horarios configurados.</p>
          : seatConfig.makeup.map(s => (
            <SeatRow
              key={s.key}
              label={s.label}
              moduleId={s.moduleId}
              courseName={s.label}
              initialSeats={s.seats}
              isNew={s.isNew}
            />
          ))
        }
      </Section>

      {/* ── Inventory: Other courses (no category) ── */}
      {seatConfig.other.length > 0 && (
        <Section title="Lugares por Curso — Otros">
          {seatConfig.other.map(s => (
            <SeatRow
              key={s.key}
              label={s.label}
              moduleId={s.moduleId}
              courseName={s.label}
              initialSeats={s.seats}
              isNew={s.isNew}
            />
          ))}
        </Section>
      )}

      {/* ── Orphaned Modulos entries (not linked to any CourseSettings course) ── */}
      {seatConfig.orphaned.length > 0 && (
        <Section title="Entradas sin curso asociado (legado)">
          <p style={{ ...emptyStyle, marginBottom: '10px' }}>
            Estas entradas existen en la base de datos pero no corresponden a ningún curso activo. Puedes eliminarlas de forma permanente.
          </p>
          {seatConfig.orphaned.map(s => (
            <OrphanRow
              key={`${s.moduleId}-${s.courseName}`}
              label={s.courseName}
              moduleId={s.moduleId}
              courseName={s.courseName}
              onDeleted={() => setSeatList(prev => prev.filter(r => r.courseName !== s.courseName))}
            />
          ))}
        </Section>
      )}

      {/* ── Global pricing ── */}
      <Section title="Precios Globales">
        <SettingRow label="Cuota de Inscripción (Q)"    settingKey="enrollmentFee" initial={settings.enrollmentFee?.value    ?? ''} type="number" />
        <SettingRow label="Precio del Kit de Pieles (Q)" settingKey="kitPrice"      initial={settings.kitPrice?.value          ?? ''} type="number" />
      </Section>

      {/* ── Kit description ── */}
      <Section title="Descripción del Kit de Pieles Perfectas">
        <KitDescriptionRow initialText={settings.kitDescription?.value ?? ''} />
      </Section>

      {/* ── Security ── */}
      <Section title="Seguridad">
        <SettingRow label="PIN de Seguridad (Finanzas)" settingKey="adminPin" initial={settings.adminPin?.value ?? '1234'} type="password" />
      </Section>

      {/* ── Site notice ── */}
      <Section title="Aviso del Sitio">
        <SiteNoticeRow
          initialText={settings.siteNotice?.value           ?? ''}
          initialActive={
            settings.siteNoticeActive?.value === true ||
            settings.siteNoticeActive?.value === 'true'
          }
        />
      </Section>

      {/* ── Activity log ── */}
      <Section title="Registro de Actividad">
        <ActivityLog />
      </Section>
    </div>
  );
}

// ── Per-seat row ─────────────────────────────────────────────────────────────

function SeatRow({ label, moduleId, courseName, initialSeats, isNew }) {
  const [value,  setValue]  = useState(initialSeats);
  const [saving, setSaving] = useState(false);
  const [saved,  setSaved]  = useState(false);
  const [err,    setErr]    = useState(null);

  const handleSave = async () => {
    if (!moduleId) { setErr('ID de módulo no encontrado.'); return; }
    setSaving(true); setErr(null); setSaved(false);
    try {
      await apiPut(`/admin/seats/${moduleId}`, { courseName, seats: Number(value) });
      setSaved(true);
      setTimeout(() => setSaved(false), 3000);
    } catch {
      setErr('Error al guardar.');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div style={rowStyle}>
      <span style={{ flex: 1, fontSize: '0.84rem', fontFamily: FONT }}>
        {label}
        {isNew && (
          <span style={{
            marginLeft: '8px', fontSize: '0.65rem', fontWeight: 700,
            padding: '2px 7px', background: '#fffbeb', border: '1px solid #fcd34d',
            color: '#92400e', fontFamily: FONT, verticalAlign: 'middle',
          }}>
            NUEVO — sin cupos configurados
          </span>
        )}
      </span>
      <input
        type="number"
        value={value}
        min="0"
        onChange={e => setValue(e.target.value)}
        style={{ ...numInput }}
      />
      <SaveButton saving={saving} saved={saved} onClick={handleSave} />
      {err && <span style={errStyle}>{err}</span>}
    </div>
  );
}

// ── Orphan row (delete-only, no seat editing) ────────────────────────────────

function OrphanRow({ label, moduleId, courseName, onDeleted }) {
  const [deleting, setDeleting] = useState(false);
  const [err,      setErr]      = useState(null);

  const handleDelete = async () => {
    setDeleting(true); setErr(null);
    try {
      await apiDelete(`/admin/seats/${moduleId}`, { courseName });
      onDeleted();
    } catch {
      setErr('Error al eliminar.');
      setDeleting(false);
    }
  };

  return (
    <div style={{ ...rowStyle, gap: '12px' }}>
      <span style={{ flex: 1, fontSize: '0.84rem', fontFamily: FONT, color: '#999' }}>{label}</span>
      <button
        onClick={handleDelete}
        disabled={deleting}
        style={{
          background:  deleting ? '#eee' : '#fff5f5',
          color:       deleting ? '#aaa' : '#9b1c1c',
          border:      '1px solid #fed7d7',
          padding:     '5px 16px',
          cursor:      deleting ? 'not-allowed' : 'pointer',
          fontSize:    '0.78rem',
          fontFamily:  FONT,
          fontWeight:  600,
        }}
      >
        {deleting ? 'Eliminando…' : 'Eliminar'}
      </button>
      {err && <span style={errStyle}>{err}</span>}
    </div>
  );
}

// ── Site setting row ──────────────────────────────────────────────────────────

const PRICE_SETTINGS = ['enrollmentFee', 'kitPrice', 'adminPin'];

function SettingRow({ label, settingKey, initial, type = 'text' }) {
  const [value,     setValue]     = useState(initial);
  const [saving,    setSaving]    = useState(false);
  const [saved,     setSaved]     = useState(false);
  const [err,       setErr]       = useState(null);
  const [pinAction, setPinAction] = useState(null);

  const handleSave = async () => {
    setSaving(true); setErr(null); setSaved(false);
    try {
      await apiPut(`/admin/site-settings/${settingKey}`, { value });
      setSaved(true);
      setTimeout(() => setSaved(false), 3000);
    } catch {
      setErr('Error al guardar.');
    } finally {
      setSaving(false);
    }
  };

  const triggerSave = () => {
    if (PRICE_SETTINGS.includes(settingKey)) {
      setPinAction(() => handleSave);
    } else {
      handleSave();
    }
  };

  return (
    <div style={rowStyle}>
      <span style={{ flex: 1, fontSize: '0.84rem', fontFamily: FONT }}>{label}</span>
      <input
        type={type}
        value={value}
        onChange={e => setValue(e.target.value)}
        style={{ ...numInput, width: '130px' }}
      />
      <SaveButton saving={saving} saved={saved} onClick={triggerSave} />
      {err && <span style={errStyle}>{err}</span>}
      <SecurityPinModal
        isOpen={!!pinAction}
        onSuccess={() => { const ac = pinAction; setPinAction(null); if (ac) ac(); }}
        onClose={() => setPinAction(null)}
        message="Estás modificando un precio o configuración sensible. Ingresa el PIN de seguridad."
      />
    </div>
  );
}

// ── Site notice (text + toggle) ───────────────────────────────────────────────

function SiteNoticeRow({ initialText, initialActive }) {
  const [text,   setText]   = useState(initialText);
  const [active, setActive] = useState(initialActive);
  const [saving, setSaving] = useState(false);
  const [saved,  setSaved]  = useState(false);
  const [err,    setErr]    = useState(null);

  const handleSave = async () => {
    setSaving(true); setErr(null); setSaved(false);
    try {
      await Promise.all([
        apiPut('/admin/site-settings/siteNotice',       { value: text }),
        apiPut('/admin/site-settings/siteNoticeActive', { value: String(active) }),
      ]);
      setSaved(true);
      setTimeout(() => setSaved(false), 3000);
    } catch {
      setErr('Error al guardar.');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div>
      <div style={{ marginBottom: '10px' }}>
        <label style={labelStyle}>Texto del aviso</label>
        <textarea
          value={text}
          onChange={e => setText(e.target.value)}
          rows={3}
          placeholder="Ej: Registro abierto — próximo módulo comienza el lunes"
          style={{ width: '100%', padding: '8px 10px', border: '1px solid #ddd', borderRadius: '0', fontSize: '0.85rem', fontFamily: FONT, boxSizing: 'border-box', resize: 'vertical', outline: 'none' }}
        />
      </div>
      <div style={{ display: 'flex', alignItems: 'center', gap: '16px', flexWrap: 'wrap' }}>
        <label style={{ display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer', fontSize: '0.84rem', fontFamily: FONT, userSelect: 'none' }}>
          <div
            onClick={() => setActive(v => !v)}
            style={{
              width: '38px', height: '20px', borderRadius: '10px',
              background: active ? '#7D4E61' : '#ccc',
              position: 'relative', transition: 'background 0.2s', cursor: 'pointer', flexShrink: 0,
            }}
          >
            <div style={{
              width: '14px', height: '14px', borderRadius: '50%', background: '#fff',
              position: 'absolute', top: '3px',
              left: active ? '21px' : '3px',
              transition: 'left 0.2s',
            }} />
          </div>
          Mostrar aviso en el sitio público
        </label>
        <SaveButton saving={saving} saved={saved} onClick={handleSave} wide />
        {err && <span style={errStyle}>{err}</span>}
      </div>
    </div>
  );
}

// ── Activity Log ─────────────────────────────────────────────────────────────

function ActivityLog() {
  const [entries,  setEntries]  = useState([]);
  const [loading,  setLoading]  = useState(true);
  const [error,    setError]    = useState(null);

  const load = () => {
    setLoading(true);
    setError(null);
    apiFetch('/admin/activity-log')
      .then(data => setEntries(Array.isArray(data) ? data : []))
      .catch(() => setError('Error al cargar el registro. Asegúrate de que la tabla AdminLog existe en DynamoDB.'))
      .finally(() => setLoading(false));
  };

  useEffect(() => { load(); }, []);

  const fmtTs = ts => ts
    ? new Date(ts).toLocaleString('es-GT', { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })
    : '—';

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
        <p style={{ margin: 0, fontSize: '0.8rem', color: '#999', fontFamily: FONT }}>
          Últimas 100 acciones de administración.
        </p>
        <button
          onClick={load}
          disabled={loading}
          style={{ background: '#fff', border: '1px solid #ddd', borderRadius: '0', padding: '5px 12px', cursor: loading ? 'default' : 'pointer', fontSize: '0.75rem', fontFamily: FONT, opacity: loading ? 0.6 : 1 }}
        >
          {loading ? 'Cargando…' : 'Actualizar'}
        </button>
      </div>

      {error && <p style={{ color: '#c62828', fontSize: '0.82rem', fontFamily: FONT }}>{error}</p>}

      {!loading && !error && entries.length === 0 && (
        <p style={{ color: '#bbb', fontSize: '0.82rem', fontFamily: FONT }}>
          No hay entradas aún. Las acciones del panel (guardar cursos, editar precios, etc.) aparecerán aquí.
        </p>
      )}

      {entries.length > 0 && (
        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.78rem', fontFamily: FONT }}>
            <thead>
              <tr style={{ borderBottom: '2px solid #f0f0f0' }}>
                <th style={thStyle}>Fecha</th>
                <th style={thStyle}>Usuario</th>
                <th style={thStyle}>Acción</th>
                <th style={thStyle}>Valor anterior</th>
                <th style={thStyle}>Nuevo valor</th>
              </tr>
            </thead>
            <tbody>
              {entries.map((e, i) => (
                <tr key={e.actionId || i} style={{ borderBottom: '1px solid #f5f5f5', background: i % 2 === 0 ? '#fafafa' : '#fff' }}>
                  <td style={tdStyle}>{fmtTs(e.timestamp)}</td>
                  <td style={tdStyle}>{e.staffEmail || '—'}</td>
                  <td style={tdStyle}>{e.action || '—'}</td>
                  <td style={{ ...tdStyle, color: '#c62828', maxWidth: '180px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{e.oldValue ?? '—'}</td>
                  <td style={{ ...tdStyle, color: '#2e7d32', maxWidth: '180px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{e.newValue ?? '—'}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

// ── Kit description textarea ──────────────────────────────────────────────────

function KitDescriptionRow({ initialText }) {
  const [text,   setText]   = useState(initialText);
  const [saving, setSaving] = useState(false);
  const [saved,  setSaved]  = useState(false);
  const [err,    setErr]    = useState(null);

  const handleSave = async () => {
    setSaving(true); setErr(null); setSaved(false);
    try {
      await apiPut('/admin/site-settings/kitDescription', { value: text });
      setSaved(true);
      setTimeout(() => setSaved(false), 3000);
    } catch {
      setErr('Error al guardar.');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div>
      <label style={labelStyle}>
        Descripción visible en el acordeón "¿Qué incluye el Kit?" de los cursos de maquillaje
      </label>
      <textarea
        value={text}
        onChange={e => setText(e.target.value)}
        rows={5}
        placeholder="Ej: El kit incluye una base, corrector, labiales, pinceles profesionales y más..."
        style={{
          width: '100%', padding: '8px 10px', border: '1px solid #ddd',
          borderRadius: '0', fontSize: '0.85rem', fontFamily: FONT,
          boxSizing: 'border-box', resize: 'vertical', outline: 'none',
          marginBottom: '10px', marginTop: '6px', lineHeight: '1.5',
        }}
      />
      <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
        <SaveButton saving={saving} saved={saved} onClick={handleSave} wide />
        {err && <span style={errStyle}>{err}</span>}
      </div>
    </div>
  );
}

// ── Shared primitives ─────────────────────────────────────────────────────────

function Section({ title, children }) {
  return (
    <div style={{ background: '#fff', border: '1px solid #e0e0e0', borderRadius: '0', padding: '18px 20px', marginBottom: '18px' }}>
      <h2 style={{ fontSize: '0.82rem', fontWeight: 700, marginBottom: '14px', letterSpacing: '0.5px', textTransform: 'uppercase', color: '#666', fontFamily: FONT }}>{title}</h2>
      {children}
    </div>
  );
}

function SaveButton({ saving, saved, onClick, wide }) {
  return (
    <button
      onClick={onClick}
      disabled={saving}
      style={{
        background: saved ? '#2e7d32' : '#111',
        color: '#fff', border: 'none', borderRadius: '0',
        padding: wide ? '8px 18px' : '7px 14px',
        cursor: saving ? 'default' : 'pointer',
        fontSize: '0.78rem', fontFamily: FONT, fontWeight: 600,
        whiteSpace: 'nowrap', opacity: saving ? 0.6 : 1,
        minWidth: '80px',
        transition: 'background 0.3s',
      }}
    >
      {saving ? '…' : saved ? '✓ Guardado' : 'Guardar'}
    </button>
  );
}

const FONT         = "'Montserrat', sans-serif";
const pageTitleStyle = { fontFamily: "'Montserrat', sans-serif", fontSize: '2.8rem', fontWeight: 300, letterSpacing: '5px', textTransform: 'uppercase', color: '#000000', margin: '0 0 22px 0' };
const labelStyle   = { display: 'block', fontSize: '0.7rem', fontWeight: 700, marginBottom: '5px', color: '#666', textTransform: 'uppercase', letterSpacing: '0.5px', fontFamily: FONT };
const rowStyle     = { display: 'flex', alignItems: 'center', gap: '12px', padding: '10px 0', borderBottom: '1px solid #f5f5f5', flexWrap: 'wrap' };
const numInput     = { width: '90px', padding: '6px 8px', border: '1px solid #ddd', borderRadius: '0', fontSize: '0.85rem', fontFamily: FONT, outline: 'none', textAlign: 'right' };
const errStyle     = { fontSize: '0.72rem', color: '#c62828', fontFamily: FONT };
const emptyStyle   = { fontSize: '0.82rem', color: '#bbb', fontFamily: FONT, margin: 0 };
const thStyle      = { textAlign: 'left', padding: '6px 10px', fontWeight: 700, color: '#666', fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.5px', whiteSpace: 'nowrap' };
const tdStyle      = { padding: '7px 10px', color: '#444', verticalAlign: 'top' };
